version: 2

sources: 
  - name: public
    description: A Redshift database
    database: production
    tables:
      - name: alkhorayef_cams
        description: akhorayef widing cameras table
        loaded_at_field: start_time
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 48, period: hour}
      - name: alkhorayef_zone
        description: akhorayef widing zone table
        loaded_at_field: col_timestamp
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 48, period: hour}
      - name: al_capacity
        description: akhorayef new capacity table
        loaded_at_field: timestamp_first_observation
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 48, period: hour}
      - name: al_housing_old
        description: akhorayef old capacity table
        loaded_at_field: timestamp_first_observation
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 48, period: hour}